---
title: "Advanced Bioinformatics 2019 assessment"
author: '21048482'
date: "2022-07-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Task 3.1  Using the sum() function and : operator, write an expression in the code snippet to evaluate the sum of all integers between 5 and 55.
sum (5:55)
# Task 3.2. Write a function called sumfun with one input parameter, called n, that  calculates the sum of all integers between 5 and n. Use the function to do the calculation for n = 10, n = 20, and n = 100 and present the results. 
sumfun <- function(n) {sum(5:n)}
sumfun(10)
sumfun (20)
sumfun (100)
# Task 3.3. The famous Fibonacci series is calculated as the sum of the two preceding members of the sequence, where the first two steps in the sequence are 1, 1. Write an R script using a for loop to calculate and print out the first 12 entries of the Fibonacci series.
fib <- function(n) {  # function for calculating fibonnaci of a vector with n values
  fib <-numeric(n)
  fib[1] <- 1 # fib of the first element is 1
  fib[2] <- 1 # fib of the second element is 2
  i = 3 # start the loop at the third element
  
  while (i <= n) { # repeat the loop for the nth  element of fib
  fib[i]=fib[i - 1] + fib[i - 2]
  i<- i + 1
 }
 return(fib) # return the modified vector
}

fib(12)
# Task 3.4. With the mtcars dataset bundled with R, use ggplot to generate a box of miles per gallon (in the variable mpg) as a function of the number of gears (in the variable gear). Use the fill aesthetic to colour bars by number of gears. 

library(ggplot2)
ggplot(data = mtcars, aes(x= as.factor(gear), y= mpg)) + geom_boxplot(aes(fill= as.factor(gear) )) + ggtitle(" Box plot of Miles per gallon(mpg) as a function of gears")
# Task 3.5. Using the cars dataset and the function lm, fit a linear relationship between speed and breaking distance in the variable distance. What are the fitted slope and intercept of the line, and their standard errors? What are the units used for the variables in the dataset?
y <- cars $dist; x <- cars $speed; 
model <- lm(formula = "y ~ x")
summary(model)

# Answers
# Fitted slope=3.9324
# Intercept = -17.579
# Standard errors ( 6.7584,0.4155)
# Speed units = milesperhour breaking distance = feet

# Task 3.6. Use ggplot to plot the data points from Task 6 and the linear fit.
library(ggplot2) 
#Assign the ggplot function to the variable ggplot_01
ggplot_1.0 <- ggplot(data = cars, aes(x= speed, y=dist)) + geom_point() + geom_smooth(method = "lm",formula = "y ~ x")
# Create a new variable called ggplplot_1.1 and add to it a title, x,y labels.
ggplot_1.1 <- ggplot_1.0 + ggtitle ("Linear model of the relationship between breaking distance(dist) and speed")+ xlab("speed(milesperhour)")+ ylab("dist(feet)")
ggplot_1.1

# Task 3.7. Again using the cars dataset, now use linear regression (lm) to estimate the average reaction time for the driver to start breaking (in seconds). To simplify matters you may assume that once breaking commences, breaking distance is proportional to the square of the speed. Explain the steps in your analysis. Do you get reasonable results? Finally, use ggplot to plot the data points and the fitted relationship.
# Assign the variable "dist_m" to breaking distance, which is the distance in miles    
    dist_m <- cars$dist* 0.000189 # converting distance to miles by multiplying by the value of one foot in miles
# Create a variable "speed_m_h" for speed in miles per hour
    speed_m_h <- cars $speed^2  #Since breaking distance is proportional to the square of speed, square the value of 
  lm(formula = dist_m ~ speed_m_h) #creating the linear model 
## 
## Call:
## lm(formula = dist_m ~ speed_m_h)
## 
## Coefficients:
## (Intercept)    speed_m_h  
##   1.675e-03    2.438e-05
    #From the model,slope is equal to half the average reaction time, if the speed and the distance are constant
    reaction_time <- 2.438e-05*2 
    # So reaction time is therefore equal to two times the value of the slope reaction_time
    #Converting reaction time in hours to seconds
    coverted_reaction_time <- reaction_time/3600
    coverted_reaction_time  
    # Answer: there's  a negative value for reaction time?
    
 library(ggplot2)
    plot_1 <- ggplot(data = cars, aes(speed_m_h, dist_m))+geom_point() 
    plot_2 <- plot_1 + geom_smooth(method = "lm", formula = dist_m ~ speed_m_h)
    plot_3 <- plot_2 + ggtitle("Regression model between breaking distance and speed")
    plot_3
  # I don't know why there's less???
  git commit m 
  
  
